name: run on issues

on:
  issues:
  workflow_dispatch:
    

jobs:
  issue_details:
    name: issue details
    runs-on: ubuntu-22.04
    steps:
      - name: issue details
        run: echo "{{ toJSON(github.event) }}"