name: lint, test, deploy

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: build, lint, test, deploy
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: deploy
        run: |
          echo "deploying...."
          sleep 5
          echo "deployed successfully"
